# Generated by Django 3.2.7 on 2021-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentpage_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='heading',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_heading',
            field=models.BooleanField(default=True),
        ),
    ]
