# Generated by Django 3.2.7 on 2021-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210919_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_subheading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='subheading',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
