# Generated by Django 4.0.2 on 2022-03-27 14:43

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contentpagesections'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpagesections',
            name='section_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentpagesections',
            name='section_heading',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
