# Generated by Django 4.0.2 on 2022-03-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentpagesections_section_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='show_subheading',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='subheading',
        ),
    ]
