# Generated by Django 4.0.2 on 2022-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_contentpage_cover_contentpagesections_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_body',
            field=models.BooleanField(default=True),
        ),
    ]
