# Generated by Django 4.0.3 on 2022-03-28 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_rename_section_body_contentpagesections_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpagesections',
            name='link',
            field=models.CharField(default=uuid.UUID('2378c03f-0a32-44f5-8268-2e5b085b04d9'), editable=False, max_length=36),
        ),
    ]
