# Generated by Django 4.0.3 on 2022-03-28 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contentpagesections_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpagesections',
            name='link',
            field=models.CharField(default=uuid.UUID('ba7c57ef-0e7e-4a96-a4c4-0640fdffe4c8'), editable=False, max_length=36),
        ),
    ]
