# Generated by Django 4.0.3 on 2022-03-28 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_contentpagesections_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpagesections',
            name='link',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
