# Generated by Django 4.0.2 on 2022-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_contentpagesections_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='show_body',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='show_heading',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_content',
            field=models.BooleanField(default=True),
        ),
    ]
