# Generated by Django 4.0.2 on 2022-04-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_contentpage_show_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'statische Seite'},
        ),
    ]
