# Generated by Django 3.2.7 on 2021-09-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='image',
            new_name='cover',
        ),
    ]
