# Generated by Django 4.0.2 on 2022-04-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_image_blogpage_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Beitragsübersicht'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Beitrag'},
        ),
    ]
