# Generated by Django 4.0.2 on 2022-04-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogindexpage_options_alter_blogpage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='show_description',
            new_name='show_content',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='heading',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
