# Generated by Django 4.0.2 on 2022-04-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0009_alter_blogpage_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='collection',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='col',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
    ]
