# Generated by Django 4.0.2 on 2022-04-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpage_collection_blogpage_col'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='col',
            new_name='collection',
        ),
    ]
