# Generated by Django 3.1.7 on 2021-03-21 18:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='actual',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
