# Generated by Django 3.1.7 on 2021-07-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_showactual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='showActual',
            new_name='show_actual',
        ),
    ]
