# Generated by Django 4.0.2 on 2022-02-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_carouselimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimages',
            old_name='caruosel_image',
            new_name='carousel_image',
        ),
    ]
