# Generated by Django 4.0.2 on 2022-02-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_caruosel_image_carouselimages_carousel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='welcome',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='show_welcome',
            new_name='show_alert',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
