# Generated by Django 4.0.2 on 2022-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_welcome_homepage_alert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Startseite'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
