# Generated by Django 4.0.2 on 2022-04-02 18:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepage_video_url_homepage_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_alert',
        ),
        migrations.AddField(
            model_name='homepage',
            name='info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
