# Generated by Django 4.0.2 on 2022-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_homepage_alert_remove_homepage_show_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
