# Generated by Django 4.0.2 on 2022-04-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_collections_alter_homepage_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='collections',
            field=models.CharField(blank=True, choices=[(1, 'Root'), (2, 'Blog Bilder'), (4, 'Blog Dokumente'), (3, 'Content Bilder'), (5, 'Content Dokumente'), (6, 'Karussell')], max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
