# Generated by Django 4.0.2 on 2022-04-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_collections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='collections',
            new_name='collection',
        ),
    ]
