# Generated by Django 4.0.2 on 2022-04-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_collections_homepage_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='year_in_school',
        ),
    ]
