# Generated by Django 4.0.2 on 2022-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepage_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='collection',
            field=models.CharField(blank=True, choices=[('1', 'Root'), ('2', 'Blog Bilder'), ('4', 'Blog Dokumente'), ('3', 'Content Bilder'), ('5', 'Content Dokumente'), ('6', 'Karussell')], max_length=255),
        ),
    ]
