# Generated by Django 4.0.3 on 2022-04-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='collection',
            field=models.CharField(blank=True, choices=[('1', 'Root')], max_length=255),
        ),
    ]
