# Generated by Django 4.1.1 on 2022-09-18 12:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeitbildPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('teamwork', wagtail.fields.RichTextField(blank=True)),
                ('community', wagtail.fields.RichTextField(blank=True)),
                ('trust', wagtail.fields.RichTextField(blank=True)),
                ('learning', wagtail.fields.RichTextField(blank=True)),
                ('schoollife', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Leitbild',
            },
            bases=('wagtailcore.page',),
        ),
    ]
